services:
  unbound:
    image: unbound
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "443:443/tcp"
      - "853:853/tcp"
    build:
      context: unbound
      dockerfile: Dockerfile

  bind9:
    image: bind9
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "443:443/tcp"
      - "853:853/tcp"
    build:
      context: bind9
      dockerfile: Dockerfile
